using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Accord.Statistics.Models.Regression;
using Accord.Statistics.Models.Regression.Fitting;
using Accord.Statistics.Models.Regression.Linear;
using Accord.Math.Optimization.Losses;
using System.IO;

namespace Classifier
{
    class Program
    {
        static private void writeCSVfile(RegressionData data, double[][] r2)
        {
            const string OUTPUT_FILE = "WeightMatrix.csv";
            string textForFile = "";
            for (int i = 0; i < data.InterestOrder.Count; i++)
            {
                textForFile += i == data.InterestOrder.Count - 1 ? data.InterestOrder[i].ToString() + Environment.NewLine : data.InterestOrder[i].ToString() + ", ";
            }
            for (int i = 0; i < data.MajorOrder.Count; i++)
            {
                textForFile += i == data.MajorOrder.Count - 1 ? data.MajorOrder[i].ToString() + Environment.NewLine : data.MajorOrder[i].ToString() + ", ";
            }
            for (int i = 0; i < r2.Length; i++)
            {
                for (int j = 0; j < r2[i].Length; j++)
                {
                    textForFile += j == r2[i].Length - 1 ? r2[i][j].ToString() : r2[i][j].ToString() + ", ";
                }
                textForFile += Environment.NewLine;
            }
            File.WriteAllText(Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName + OUTPUT_FILE, textForFile);
        }

        static private void GenerateCSFile(RegressionData data, double[][] r2)
        {
            const string OUTPUT_FILE = "\\Weights.cs";
            StringBuilder CSfileContents = new StringBuilder(10000);
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("//Generated by TamuyalClassifier: https://github.com/Kaikat/TamuyalClassifier");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("using System;");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("namespace WebApplication1.Controllers");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("{");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("\tpublic static class Weights");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("\t{");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("\t\tpublic static readonly double[][] Matrix =");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("\t\t{");
            CSfileContents.Append(Environment.NewLine);

            //append matrix values
            string textForFile = "";
            for (int i = 0; i < r2.Length; i++)
            {
                textForFile += "\t\t\tnew double[] { ";
                for (int j = 0; j < r2[i].Length; j++)
                {
                    if (j % 4 == 0)
                    {
                        textForFile += Environment.NewLine + "\t\t\t\t";
                    }
                    textForFile += j == r2[i].Length - 1 ? r2[i][j].ToString() : r2[i][j].ToString() + ", ";
                }
                textForFile += i == r2.Length - 1 ? Environment.NewLine + "\t\t\t}" : Environment.NewLine + "\t\t\t},";
                textForFile += Environment.NewLine;
            }

            CSfileContents.Append(textForFile);
            CSfileContents.Append("\t\t};");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("\t};");
            CSfileContents.Append(Environment.NewLine);
            CSfileContents.Append("};");
            File.WriteAllText(Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName + 
                OUTPUT_FILE, CSfileContents.ToString());
        }

        //EXAMPLE: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Regression_Linear_MultivariateLinearRegression.htm
        static void Main(string[] args)
        {
            /*const int NUM_ROWS = 5;
            const int NUM_TOPICS = 12;
            const int NUM_MAJORS = 26;

            double[][] topicRatings = {              
                new double[] { 1.0, 1.0, 1.0 },
                new double[] { 2.1, 1.0, 1.0 },
                new double[] { 3.7, 1.0, 1.0 },
                
                new double[] { 4.2, 1.0, 1.0 },
                new double[] { 5.5, 1.0, 1.0 }
            };
            


            double[][] majorRatings = new double[][] {
                new double[] { 2.0, 3.0 },
                new double[] { 4.0, 6.0 },
                new double[] { 6.0, 9.0 },
                
                new double[] { 8.0, 12.0 },
                new double[] { 10.0, 15.0 }
            };*/

            CSV_Parser parser = new CSV_Parser();
            RegressionData data = parser.ParseDataFile();


            // Use Ordinary Least Squares to create the regression
            OrdinaryLeastSquares ols = new OrdinaryLeastSquares();

            // Now, compute the multivariate linear regression:
            MultivariateLinearRegression regression = ols.Learn(data.InterestRatings, data.MajorRatings);

            // We can obtain predictions using
            double[][] predictions = regression.Transform(data.InterestRatings);

            // The prediction error is
            double error = new SquareLoss(data.MajorRatings).Loss(predictions); // 0

            // We can also check the r-squared coefficients of determination:
            //double[] r2 = regression.CoefficientOfDetermination(topicRatings, majorRatings);
            double[][] r2 = regression.Weights;
            Console.WriteLine("WEIGHTS:");
            //writeCSVfile(data, r2);
            GenerateCSFile(data, r2);

            Console.WriteLine("Coefficient Of Determination");
            double[] r3 = regression.CoefficientOfDetermination(data.InterestRatings, data.MajorRatings);
            for(int i = 0; i < r3.Length; i++)
            {
                Console.WriteLine(r3[i]);
            }









































            /*new [] { 4.0, 3.0, 4.0, 3.0, 4.0, 3.0, 4.0, 5.0, 3.0, 2.0, 3.0, 4.0 },
new [] { 4.0, 4.0, 3.0, 3.0, 4.0, 5.0, 4.0, 5.0, 3.0, 4.0, 2.0, 3.0 },
new [] { 2.0, 5.0, 4.0, 2.0, 3.0, 5.0, 3.0, 5.0, 2.0, 4.0, 3.0, 1.0 },
new [] { 4.0, 4.0, 4.0, 2.0, 4.0, 5.0, 5.0, 5.0, 1.0, 2.0, 5.0, 4.0 },
new [] { 3.0, 5.0, 3.0, 4.0, 3.0, 4.0, 5.0, 5.0, 1.0, 4.0, 5.0, 1.0 }
*/


            /*
new double[] { 3.0, 3.0, 4.0, 4.0, 2.0, 3.0, 2.0, 4.0, 3.0, 4.0, 2.0, 2.0, 2.0, 1.0, 3.0, 1.0, 5.0, 3.0, 3.0, 1.0, 3.0, 2.0, 2.0, 3.0, 1.0, 4.0 },
new double[] { 2.0, 1.0, 4.0, 3.0, 5.0, 3.0, 2.0, 2.0, 3.0, 3.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 5.0, 3.0, 4.0, 1.0, 1.0, 3.0, 1.0, 3.0, 3.0, 4.0 },
new double[] { 1.0, 1.0, 2.0, 3.0, 2.0, 2.0, 2.0, 4.0, 2.0, 2.0, 3.0, 2.0, 2.0, 1.0, 4.0, 1.0, 4.0, 4.0, 4.0, 1.0, 3.0, 4.0, 4.0, 4.0, 1.0, 5.0 },
new double[] { 2.0, 1.0, 1.0, 4.0, 4.0, 1.0, 3.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 5.0, 3.0, 5.0, 4.0, 1.0, 4.0, 1.0, 4.0, 1.0, 4.0, 1.0, 4.0 },
new double[] { 1.0, 1.0, 4.0, 4.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.0, 1.0, 5.0, 4.0, 5.0, 1.0, 5.0, 3.0, 2.0, 1.0, 2.0, 4.0, 3.0, 4.0, 1.0, 3.0 }
*/

































            /* double[] topicsSqrt = new double[NUM_ROWS];
             double[] majorsSqrt = new double[NUM_ROWS];
             for(int i = 0; i < NUM_ROWS; i++)
             {
                 double total = 0;
                 for(int j = 0; j < NUM_TOPICS; j++)
                 {
                     total += (topicRatings[i][j] * topicRatings[i][j]);
                 }
                 topicsSqrt[i] = Math.Sqrt(total);

                 total = 0;
                 for(int k = 0; k < NUM_MAJORS; k++)
                 {
                     total += (majorRatings[i][k] * majorRatings[i][k]);
                 }
                 majorsSqrt[i] = Math.Sqrt(total);
             }
             for(int i = 0; i < NUM_ROWS; i++)
             {
                 for(int j = 0; j < NUM_TOPICS; j++)
                 {
                     topicRatings[i][j] = topicRatings[i][j] / topicsSqrt[i];
                 }
                 for(int k = 0; k < NUM_MAJORS; k++)
                 {
                     majorRatings[i][k] = majorRatings[i][k] / majorsSqrt[i];
                 }
             }
             // Create a new Multinomial Logistic Regression for 3 categories
             var regression = new MultinomialLogisticRegression(inputs: NUM_TOPICS, categories: NUM_MAJORS);

             // Create a estimation algorithm to estimate the regression
             LowerBoundNewtonRaphson lbnr = new LowerBoundNewtonRaphson(regression);
             MultinomialLogisticRegression delta = lbnr.Learn(topicRatings, majorRatings);

             double[] results = new double[NUM_MAJORS];
             results = delta.Probabilities(topicRatings[0], results);

             for(int i = 0; i < results.Length; i++)
             {
                 Console.WriteLine(results[i].ToString());
             }
             */
            Console.Read();
        }
    }
}
